# Generated by Django 2.2.7 on 2020-05-20 05:50

from django.db import migrations, models
import sassignments.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Grade', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=100)),
                ('Section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=100)),
                ('Admission_Number', models.CharField(max_length=100)),
                ('Content', models.FileField(upload_to=sassignments.models.get_form_path)),
                ('Assignment_Code', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='view_assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Assignment_Code', models.CharField(max_length=10)),
            ],
        ),
    ]
