# Generated by Django 2.2.7 on 2020-05-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=100)),
                ('Subject_Name', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Mathematics', 'Mathematics'), ('Physics', 'Physcis'), ('Chemistry', 'Chemistry'), ('Computer Science', 'Computer Science'), ('Biology', 'Biology'), ('History', 'History'), ('Geography', 'Geography'), ('Civics', 'Civics'), ('Economics', 'Economics'), ('Political Science', 'Political Science'), ('Business Studies', 'Business Studies'), ('Accountancy', 'Accountancy'), ('Sanskrit', 'Sanskrit'), ('Social Studies', 'Social Studies'), ('EVS', ' EVS')], max_length=100)),
            ],
        ),
    ]
